---
# This is an example playbook to execute Ansible tests.
- hosts: all
  gather_facts: yes

- name: Verify
  hosts: client
  vars:
    address: '{{ hostvars["minecraft-server"].ansible_default_ipv4.address }}'
  tasks:
  - name: Wait two minutes to confirm server is reachable
    command: 'mcstatus {{ address }} status'
    changed_when: false
    retries: 24
    delay: 5
    register: mcstatus_status_raw
    until: not (mcstatus_status_raw is failed)
  - name: load the mcstatus status json
    set_fact:
      mcstatus_status: '{{ mcstatus_status_raw.stdout | from_yaml }}'

  - debug: var=mcstatus_status

  - name: Query server
    command: 'mcstatus {{ address }} query'
    changed_when: false
    register: mcstatus_query_raw
  - name: load the mcstatus query json
    set_fact:
      mcstatus_query: '{{ mcstatus_query_raw.stdout | from_yaml }}'

  - name: Assert motd is properly set and reported
    assert:
      that:
      - mcstatus_query.motd == motd
      - motd in mcstatus_status.description
    vars:
      motd: '{{ hostvars["minecraft-server"].motd }}'
