---

- name: Set address on status
  when: has_route
  k8s_status:
    api_version: demos.fabianism.us/v1alpha1
    kind: Minecraft
    name: '{{ meta.name }}'
    namespace: '{{ meta.namespace }}'
    status:
      address: "{{ host }}:{{ node_port }} "
  vars:
    host: "{{ q('k8s',
        api_version='route.openshift.io/v1',
        kind='Route',
        namespace=meta.namespace,
        resource_name=meta.name + '-minecraft'
      ).0.spec.host }}"
    node_port: "{{ q('k8s',
      api_version='v1',
      kind='Service',
      namespace=meta.namespace,
      resource_name=meta.name + '-minecraft'
    ).0.spec.ports.0.nodePort }}"

- name: Set address on status
  when: not has_route
  k8s_status:
    api_version: demos.fabianism.us/v1alpha1
    kind: Minecraft
    name: '{{ meta.name }}'
    namespace: '{{ meta.namespace }}'
    status:
      address: "{{ host_ip }}:{{ node_port }}"
  vars:
    host_ip: "{{ q('k8s',
      api_version='v1',
      kind='Pod',
      namespace=meta.namespace,
      label_selector='app=' + meta.name
    ).0.status.hostIP }}"
    node_port: "{{ q('k8s',
      api_version='v1',
      kind='Service',
      namespace=meta.namespace,
      resource_name=meta.name + '-minecraft'
    ).0.spec.ports.0.nodePort }}"
